### ISSUE TITLE
rgdal missing

### ISSUE THREAD

**Issue by nuest** [vwmaus/dtwSat#1]
When I install the package from source (using tag `draft_jss001`) and try to knit the file `README.Rmd` I encounter the following issues:

### rgdal required

There seems to be an intransparent requirement to `rgdal`, which was not installed on my testing system:

```
label: unnamed-chunk-10 (with options) 
List of 2
 $ echo: logi TRUE
 $ eval: logi TRUE

Quitting from lines 123-131 (README.Rmd) 
Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  Cannot create RasterLayer object from this file; perhaps you need to install rgdal first
Calls: eval ... eval -> eval -> brick -> brick -> .rasterObjectFromFile
```

### ggplot not loaded

I need to manually load the library `ggplot2` before knitting the file. Shouldn't it be loaded from within the RMarkdown file? The problem ist that `theme_get()` function is not found otherwise.

**Comment by vwmaus** [comment]
Hi Daniel,
Thanks for the feedback. We can talk tomorrow morning.

Cheers,
Victor
