### ISSUE TITLE
Processing time

### ISSUE THREAD

**Issue by sikli** [vwmaus/dtwSat#10]
Hey! Great package! The method looks very promising!
I am currently testing it out on a Sentinel-2 tile using one year of data. 
I am doing this with the parallel processing function provided by you ("twdtwApplyParallel"), but the processing takes forever anyway. Is there any recommendation how I can speed up the process? Chunksize? Blocksize? etc?

Best regards

Martin

**Comment by vwmaus** [comment]
Hi Martin, 

DTW is a computationally expensive method. There some options in the literature to improve processing time (e.g. [fastDTW](https://pdfs.semanticscholar.org/05a2/0cde15e172fc82f32774dd0cf4fe5827cad2.pdf) ). However, most of the alternative methods use the called close boundary conditions (for details see [Müller 2007](https://www.google.at/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjYyb7QnP7UAhUEaVAKHd5jCBUQFggkMAA&url=http:%2F%2Fwww.springer.com%2Fcda%2Fcontent%2Fdocument%2Fcda_downloaddocument%2F9783540740476-c1.pdf%3FSGWID%3D0-0-45-452103-p173751818&usg=AFQjCNEoEbKBzZV-2qc3ujKtlAZuEYETng&cad=rja)). 

The function "twdtwApplyParallel" is still under test for raster files processing, but for big data, we use a database called [SciDB](http://www.paradigm4.com/). To get satellite images in SciDB, one can use the gdal plugin [scidb4gdal](https://github.com/appelmar/scidb4gdal)

How big is your area (number of cols and rows of the raster stack)? How many temporal patterns are you using? How many cores are available for you? 

Best,
Vicor
