### ISSUE TITLE
error in twdtwAssess

### ISSUE THREAD

**Issue by meteoclima** [vwmaus/dtwSat#11]
Hello, I've some problems using this function:
I define a threshold in order to let the function detecting a crop  (thresholds set at 2.5 and not Inf)
> r_class <- twdtwClassify(r_twdtw, progress = 'text', overwrite=TRUE, thresholds=2.5, overlap=0.5)
> 
> twdtw_assess <- twdtwAssess(object = r_class, y = validation_samples, proj4string = proj_str, conf.int = .95, rm.nosample = TRUE) 
Error in to - from : 
  argomento non numerico trasformato in operatore binario

but I get the error above, translated:
non numeric argument trasformed in binary operator

How can I resolve this issue ?
I would like to get statistics on the r_class.,  like percentage of land , and probability of presence of a crop.  

many thanks

**Comment by vwmaus** [comment]
Hi @meteoclima, can you send the result of the following commands:
```
packageDescription("dtwSat")$Version
str(r_class)
str(validation_samples)
str(proj_str)
```

**Comment by meteoclima** [comment]
I ve just resolved the issue, thanks
Simone
