### ISSUE TITLE
raster different from training ones

### ISSUE THREAD

**Issue by meteoclima** [vwmaus/dtwSat#12]
Hello, I've a doubt,
It's possible to let work the software on raster satellite images of dates in which I have no training samples ?
I mean, for example, in the last season I know precisely parcels in which wheat were cultivated, and from that I manage the training of the model.
In this new season (2018) , basing on the model of the last year, I want to check the probability of presence of wheat during this season.
Does it possible ?
Beacouse when I run the command to generate RasterTimeSeries, it advice me the dates are not coherent with the samples ones.....

Many thanks

Simone

**Comment by vwmaus** [comment]
@meteoclima you can use the patterns from the previous years to classify 2018. In any case, you need samples of 2018 to assess the classification results, then decide if the accuracy is satisfactory for your application.

**Comment by meteoclima** [comment]
OK, many thanks
