### ISSUE TITLE
errore in creating temporal patterns

### ISSUE THREAD

**Issue by meteoclima** [vwmaus/dtwSat#13]
Hello , 
I get this error in the phase of creation of temporal patterns applying the same formula
of the example reported here in github.

```
temporal_patterns <- createPatterns(training_ts, freq=8, formula = y~s(x))
error in smooth.construct.tp.smooth.spec(object, dk$data, dk$knots) :
 A term has fewer unique covariate combinations then specified maximum degrees of freedom

```
I ve attempted also changing the knots value but nothing changed ...
I attach the input file of timeline and samples.... if of your interests

thanks
Simone

[samples -.txt](https://github.com/vwmaus/dtwSat/files/2029571/samples.-.txt)
[samples_projection .txt](https://github.com/vwmaus/dtwSat/files/2029572/samples_projection.txt)
[timeline.txt](https://github.com/vwmaus/dtwSat/files/2029573/timeline.txt)

**Comment by vwmaus** [comment]
@meteoclima may need to change the default value of the argument `k` from the adjusted function `s`. Please see <https://stat.ethz.ch/pipermail/r-help/2007-October/143569.html> and `?mgcv::choose.k`.

**Comment by vwmaus** [comment]
@meteoclima is the issues solved?

**Comment by vwmaus** [comment]
closing inactive issues
