### ISSUE TITLE
About twdtwApplyParallel function on Linux

### ISSUE THREAD

**Issue by JieBNU** [vwmaus/dtwSat#15]
Hello, Victor

I installed the dtwSat version (v 0.2.3) on Linux again via the order:

install.packages("devtools")
devtools::install_github("vwmaus/dtwSat")

However, it still doesn't work. There is only one twdtwApply function in the dtwSat package, but no twdtwApplyParallel function. Is there anyone have the same problem?

![fig](https://user-images.githubusercontent.com/36975686/40428537-163dd240-5ed3-11e8-8280-65f92d61bf35.jpg)

thanks
Jie

**Comment by vwmaus** [comment]
@JieBNU the function `twdtwApplyParallel` is exported and should be available when you install the package (see in line 49 in the file <https://github.com/vwmaus/dtwSat/blob/master/R/twdtwApplyParallel.R>). Are you sure that your R is pointing to the correct folder where you installed the packages? You can check using `.libPaths()`

**Comment by JieBNU** [comment]
Thank you very much! It is my negligence. Now I have successfully run it on Linux.

**Comment by vwmaus** [comment]
Great, thanks @JieBNU

**Comment by vwmaus** [comment]
@JieBNU dtwSat v0.2.4 is now up to date on CRAN

**Comment by JieBNU** [comment]
Hi, Victor

Now, I am trying to submit assignments to Linux server in order to improve computational efficiency. When submit the job on one node, everything runs fine, however when I submit the same code to the multiple node, I get an error. Do you have these problems ever?

The error is below: Error in socketConnection(port = port, server = TRUE, blocking = TRUE,  : 
  cannot open the connection
Calls: beginCluster ... <Anonymous> -> <Anonymous> -> newSOCKnode -> socketConnection
In addition: Warning message:
In socketConnection(port = port, server = TRUE, blocking = TRUE,  :
  port 11829 cannot be opened
Execution halted
