### ISSUE TITLE
About multiple nodes for parallel processing

### ISSUE THREAD

**Issue by JieBNU** [vwmaus/dtwSat#18]
Hi, Victor

Now, I am trying to submit assignments to Linux server in order to improve computational efficiency. When submit the job on one node, everything runs fine, however when I submit the same code to the multiple node, I get an error. Do you have these problems ever?

The error is below: 
Error in socketConnection(port = port, server = TRUE, blocking = TRUE, :
cannot open the connection
Calls: beginCluster ... -> -> newSOCKnode -> socketConnection
In addition: Warning message:
In socketConnection(port = port, server = TRUE, blocking = TRUE, :
port 11829 cannot be opened
Execution halted

**Comment by vwmaus** [comment]
@JieBNU I need a reproducible example. Could you share your script?

**Comment by JieBNU** [comment]
@vwmaus  I really think it is difficult to run on Linux, but easier on Windows. I tried to run it on Tianhe-2 Server, but there is still all kinds of errors...  I felt devastated. Do you run it success on Linux?
The script is similar to the demo example.
[dtwSat_landsat.txt](https://github.com/vwmaus/dtwSat/files/2072265/dtwSat_landsat.txt)

**Comment by vwmaus** [comment]
Your code looks good. Using my own dataset I can run the parallel processing on Ubuntu 16.04. 

Which function returns the error message? Is it `beginCluster` or `twdtwApplyParallel`?  

If the problem comes from `beginCluster` you could have look at the argument `type` from `raster::beginCluster`, for details see `raster::beginCluster`. The default is `type="PSOCK"`. You could try `type="FORK"`, which creates a socket cluster by forking (this type is not available on Windows).

**Comment by JieBNU** [comment]
Thanks, @vwmaus . I tried to change the type="PSOCK" into "FORK", but there is still wrong:

Error in UseMethod("sendData") : 
  no applicable method for 'sendData' applied to an object of class "c('forknode', 'SOCK0node')"
Calls: twdtwApplyParallel ... clusterExport -> clusterCall -> sendCall -> postNode -> sendData
Execution halted

Then  I use the data provided in dtwSat package to run, when I use twdtwApply function, the results looks fine. However, when use twdtwApplyParallel function, it returns the error message. I guess it is twdtwApplyParallel function lead to the problem.

**Comment by vwmaus** [comment]
@JieBNU does the solution from #19 work also on Linux?

**Comment by JieBNU** [comment]
@vwmaus No, it still doesn't work. And it won't show progress bar like windows.
However, I used the code and data you provided in dtwSat demo, it worked.

**Comment by JieBNU** [comment]
@vwmaus 
hi, do you know dtwSat is belong to MPI program or OpenMP program? or MPI+OpenMP program?

**Comment by vwmaus** [comment]
`dtwSat` uses the cluster functions from `raster` package. Please see `?raster::beginCluster`.

**Comment by vwmaus** [comment]
Are your `tif` files visible to all instances of the Linux server?

**Comment by JieBNU** [comment]
@vwmaus yes, it is visible to all instances of Linux server.
It seems that dtwSat can not be cross-node parallelled.

**Comment by vwmaus** [comment]
@JieBNU I got access to a cluster where I could reproduce this error. Could you provide the scripts you are running on your cluster?

**Comment by JieBNU** [comment]
@vwmaus The scripts is basically same as the example you provided in the demo. Could you share me your script running in the cluster?
