### ISSUE TITLE
non-numeric argument to binary operator

### ISSUE THREAD

**Issue by kolrocket** [vwmaus/dtwSat#21]
Hello. I'm trying to use
mat1 = twdtwApply(x=ts2, y=ts), where ts2 and ts are both twdtwTimeSeries quarterly time series with labels index(TESTE2)<-c("1984-01-01","1984-04-01","1984-09-01","1984-12-01",
                "1985-01-01","1985-04-01","1985-09-01","1985-12-01",
                "1986-01-01","1986-04-01","1986-09-01","1986-12-01",
                "1987-01-01","1987-04-01","1987-09-01","1987-12-01",
                "1988-01-01","1988-04-01","1988-09-01","1988-12-01",...)
-ts2 has 4 columns (like in the example provided with evi, ndvi...) with 136 rows
-ts has also 4 columns with 136 rows

I keep getting this error:
Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : 
  non-numeric argument to binary operator

Any solution to my case? Thank you

**Comment by vwmaus** [comment]
@kolrocket can you provide a reproducible example as well as the result from `str(ts)` and `str(ts2)`?

**Comment by kolrocket** [comment]
Oh, thanks! It was the index which was wrong. Just adding base::as.Date in index(TESTE)<-base::as.Date(c("1984-01-01"...).... solved the problem.

However, if you could help in one more question, please... using the dataset provided by the package.
` tsA = twdtwTimeSeries(MOD13Q1.ts.list[[1]], labels = "A")`
`tsB = twdtwTimeSeries(B = MOD13Q1.ts.list[[2]])`
`mat1 = twdtwApply(x=tsA, y=tsB, weight.fun=log_fun,keep=TRUE)`
`plotMatches(mat1)`

It gives:
Warning messages:
1: In zoo(rval, index(x)[i]) :
  some methods for “zoo” objects do not work if the index entries in ‘order.by’ are not unique
2: In data.row.names(row.names, rowsi, i) :
  some row.names duplicated: 34,43,60,61,64,84,85,94,102,103,104,133,147,148 --> row.names NOT used

Why are these warnings appearing, eventhough they are unique and not duplicated?
Thanks in advance and sorry for all those questions.

**Comment by kolrocket** [comment]
Thanks for all the helping.
I said it would be the last question, however, I came up with one more, this is truly the last question, since I managed to reproduce the examples until the last part with all the helping provided.
Using the data from the package

log_weight = logisticWeight(alpha = -0.1, beta = 100)
matches = twdtwApply(x = ts, y = patterns_ts, weight.fun = log_weight, keep=TRUE) slotNames(matches)
> plot(matches, type="alignments", attr="red", patterns.labels="Soybean")
> plot(matches, type="alignments", attr="nir", patterns.labels="Soybean")
> plot(matches, type="alignments", attr="ndvi", patterns.labels="Soybean")
> plot(matches, type="alignments", attr="blue", patterns.labels="Soybean")

________________________________
De: Victor Maus <notifications@github.com>
Enviado: quinta-feira, 18 de outubro de 2018 04:22
Para: vwmaus/dtwSat
Cc: kolrocket; Mention
Assunto: Re: [vwmaus/dtwSat] non-numeric argument to binary operator (#21)


Thanks for reporting this. plotMatches() gives a warning message because matches (dashed lines in the plot) can have duplicated index, i.e., one observation in the time series can have multiple matching observations in the temporal pattern, 1:n. The other way around is also true, several observations in the time series can have the same matching in the temporal pattern, n:1. This should affect the classification or any other.

**Comment by kolrocket** [comment]
Thanks for all the helping.
I said it would be the last question, however, I came up with one more, this is truly the last question, since I managed to reproduce the examples until the last part with all the helping provided.
Using the data from the package 

`ts = twdtwTimeSeries(MOD13Q1.ts, labels="Time series")`
`log_weight = logisticWeight(alpha = -0.1, beta = 100)` 
`patterns_ts = twdtwTimeSeries(MOD13Q1.patterns.list)`
`matches = twdtwApply(x = ts, y = patterns_ts, weight.fun = log_weight, keep=TRUE)`
`plot(matches,` type="alignments", attr="red", patterns.labels="Soybean")`
`plot(matches, type="alignments", attr="nir", patterns.labels="Soybean")`
`plot(matches, type="alignments", attr="ndvi", patterns.labels="Soybean")`
`plot(matches, type="alignments", attr="blue", patterns.labels="Soybean")`

The DTW dissimilarities plot is the same for all four cases, eventhough we changed the long term time series attribute. Is this correct or is it a plot bug? 
Again, thank you, thank you very much for all the helping provided.

**Comment by kolrocket** [comment]
Thanks for all the helping.
I said it would be the last question, however, I came up with one more, this is truly the last question, since I managed to reproduce the examples until the last part with all the helping provided.
Using the data from the package

`ts = twdtwTimeSeries(MOD13Q1.ts, labels="Time series")`
`log_weight = logisticWeight(alpha = -0.1, beta = 100)`
`patterns_ts = twdtwTimeSeries(MOD13Q1.patterns.list)`
`matches = twdtwApply(x = ts, y = patterns_ts, weight.fun = log_weight, keep=TRUE)`
`plot(matches, type="alignments", attr="red", patterns.labels="Soybean")`
`plot(matches, type="alignments", attr="nir", patterns.labels="Soybean")`
`plot(matches, type="alignments", attr="ndvi", patterns.labels="Soybean")`
`plot(matches, type="alignments", attr="blue", patterns.labels="Soybean")`

The DTW dissimilarities plot is the same for all four cases, eventhough we changed the long term time series attribute. Is this correct or is it a plot bug?
Again, thank you, thank you very much for all the helping provided.

**Comment by vwmaus** [comment]
`twdtwApply()` calculates a multidimensional distance, i.e., using all bands, there is no individual alignment for each bad. The plot only allows you to visualise different bans in the plot. If you want to get the alignment for each band independently from each other you have to run `twdtwApply()` for each band. For example:
```
# red 
log_weight = logisticWeight(alpha = -0.1, beta = 100)
ts_red = twdtwTimeSeries(MOD13Q1.ts[, "red", drop = FALSE], labels="Time series")
patterns_ts_red = twdtwTimeSeries(lapply(MOD13Q1.patterns.list, function(x) x[, "red", drop = FALSE] ))
matches_red = twdtwApply(x = ts_red, y = patterns_ts_red, weight.fun = log_weight, keep=TRUE)
plot(matches_red, type="alignments", attr="red", patterns.labels="Soybean")
```

**Comment by kolrocket** [comment]
Thank you very much!

Everything is clear now :)

Em 19 de out de 2018, à(s) 04:36, Victor Maus <notifications@github.com<mailto:notifications@github.com>> escreveu:


twdtwApply() calculates a multidimensional distance, i.e., using all bands, there is no individual alignment for each bad. The plot only allows you to visualise different bans in the plot. If you want to get the alignment for each band independently from each other you have to run twdtwApply() for each band. For example:

# red
log_weight = logisticWeight(alpha = -0.1, beta = 100)
ts_red = twdtwTimeSeries(MOD13Q1.ts[, "red", drop = FALSE], labels="Time series")
patterns_ts_red = twdtwTimeSeries(lapply(MOD13Q1.patterns.list, function(x) x[, "red", drop = FALSE] ))
matches_red = twdtwApply(x = ts_red, y = patterns_ts_red, weight.fun = log_weight, keep=TRUE)
plot(matches_red, type="alignments", attr="red", patterns.labels="Soybean")
