### ISSUE TITLE
erro in twdtwAssess

### ISSUE THREAD

**Issue by Mengshiyao** [vwmaus/dtwSat#23]
Hi victor.
     I have try many times but same error still appear.

Error in twdtwAssess.twdtwRaster(object, y, labels, id.labels, proj4string,  : 
  samples starting date not found, the argument 'y' must have a column called 'from'

    the field samples .csv file was export from ENVI ROI ,i made it have the same format as your demo .csv
file, and use notepad++ transform it to UNIX format ,still don't work.
    when i open your demo samples.csv ,your header display was  "from",my header display was form without "",and,the same condition,your date was "yyyy-mm-dd",my date was yyyy/mm/dd without ""and- .
   i wonder if it's the problem ,if so, and how to solve ?
  my field sample file was "examples1.4.csv" on my github "https://github.com/Mengshiyao/dtwsat"
  Best Wishes

**Comment by Mengshiyao** [comment]
packageDescription("dtwSat")$Version
[1] "0.2.4"
> str(r_class)
Error in str(r_class) : 找不到对象'r_class'
> str(validation_samples)
'data.frame':   734 obs. of  5 variables:
 $ longitude: num  -88.3 -88.3 -88.3 -88.3 -88.3 ...
 $ latitude : num  40 40 40 40 40 ...
 $ from     : Factor w/ 1 level "2017/2/3": 1 1 1 1 1 1 1 1 1 1 ...
 $ to       : Factor w/ 1 level "2017/11/27": 1 1 1 1 1 1 1 1 1 1 ...
 $ label    : Factor w/ 7 levels "alflafa","corn",..: 6 6 6 6 6 6 6 6 6 6 ...
> str(proj_str)
 chr "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

**Comment by vwmaus** [comment]
maybe you try to convert the columns `from` and `to` from `Factor` to `character` or even better to `Date` using the function `as.Date()`.

**Comment by Mengshiyao** [comment]
[新建文件夹.zip](https://github.com/vwmaus/dtwSat/files/2524554/default.zip)
gratitude,this is all files i used.

**Comment by vwmaus** [comment]
did you try to convert the columns `from` and `to` using the function `as.Date()`?

**Comment by Mengshiyao** [comment]
field_samples <- read.csv(paste(data_folder,"example1.4.csv", sep="/",as.Date(c(from),c(to))))
Error in as.Date(c(from), c(to)) : Can not find object'from'

**Comment by Mengshiyao** [comment]
field_samples <- read.csv(paste(data_folder,"example1.4.csv", sep="/"),sep=",",quote="", header=TRUE, dec = ".",as.Date(c("from"),c("to")))
Error in Ops.Date(fill) : unary ! not defined for "Date" objects

**Comment by Mengshiyao** [comment]
i don't much about R...so..is that ritght?

**Comment by Mengshiyao** [comment]
i don't know much about R...so..is that ritght?

**Comment by vwmaus** [comment]
```
field_samples <- read.csv(paste(data_folder,"example1.4.csv", sep="/"), sep=",", quote="", header=TRUE, stringsAsFactors = FALSE)
field_samples$from = as.Date(field_samples$from)
field_samples$to = as.Date(field_samples$to)
```

**Comment by Mengshiyao** [comment]
data_folder <- system.file("champaign_stack_cut_bip_tiff",package="dtwSat")
> field_samples <- read.csv(paste(data_folder,"example1.4.csv", sep="/"), sep=",", quote="", header=TRUE, stringsAsFactors = FALSE)
> field_samples$from = as.Date(field_samples$from)
Error in as.Date.default(field_samples$from) : 
  do not know how to convert 'field_samples$from' to class “Date”
> field_samples$to = as.Date(field_samples$to)
Error in as.Date.default(field_samples$to) : 
  do not know how to convert 'field_samples$to' to class “Date”

**Comment by Mengshiyao** [comment]
A bit tricky...

**Comment by vwmaus** [comment]
provide a script which reproduces your error

**Comment by Mengshiyao** [comment]
> library(dtwSat)
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: raster
Loading required package: sp
Loading required package: snow
Loading required package: ggplot2
Loaded dtwSat v0.2.4. See ?dtwSat for help, citation("dtwSat") for use in publication.

> data_folder <- system.file("champaign_stack_cut_bip_tiff",package="dtwSat")
> field_samples <- read.csv(paste(data_folder,"example1.4.csv", sep="/"), sep=",", quote="", header=TRUE, stringsAsFactors = FALSE)
> field_samples$from = as.Date(field_samples$from)
Error in as.Date.default(x, ...) : 
  do not know how to convert 'x' to class “Date”
> field_samples$to = as.Date(field_samples$to)
Error in as.Date.default(x, ...) : 
  do not know how to convert 'x' to class “Date”

**Comment by vwmaus** [comment]
Please check what you are doing before running any code `?system.file`. You don't need the function `system.file`. Maybe you should read an [R-intro](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf).
```
library(dtwSat)
field_samples <- read.csv("example1.4.csv", sep=",", stringsAsFactors = FALSE)
field_samples$from = as.Date(field_samples$from)
field_samples$to = as.Date(field_samples$to)
```

**Comment by Mengshiyao** [comment]
> library(dtwSat)
> library(caret)
> setwd("D:/Program Files/R/R-3.5.1/library/dtwSat/champaign_stack_cut_bip_tiff")
> field_samples <- read.csv("example1.4.csv", sep=",", stringsAsFactors = FALSE)
>  field_samples$to = as.Date(field_samples$to)
> dates <- scan("timeline",what="date")
Read 15 items
>  blue <- brick("cp_blue.tif")
>   green <- brick("cp_green.tif")
>   nir <- brick("cp_nir.tif")
>   red <- brick("cp_red.tif")
>   swir1 <- brick("cp_swir1.tif")
>   swir2 <- brick("cp_swir2.tif")
>  proj_str <- scan("sample1_projection",what="character")
Read 1 item
> raster_timeseries <- twdtwRaster(blue,green,nir,red,swir1,swir2,timeline=dates)
> field_samples_ts <- getTimeSeries(raster_timeseries,y=field_samples,proj4string=proj_str)
> set.seed(1)
>  I <- unlist(createDataPartition(field_samples[,"label"],p=0.25))
> training_ts <- subset(field_samples_ts,I)
>   validation_samples <- field_samples_ts[-I,]
> temporal_patterns <-createPatterns(training_ts,freq=8,formula=y~s(x))
>  log_fun <- logisticWeight(alpha=-0.1,beta=50)
>  log_fun <- logisticWeight(alpha=-0.1,beta=50)
>  beginCluster()
8 cores detected, using 7
> twdtw_dist <- twdtwApplyParallel(x=raster_timeseries,y=temporal_patterns,overlap=0.5,weight.fun=log_fun,overwrite=TRUE,format="GTiff",progress="text"）                                           
> endCluster()
> land_cover_maps <- twdtwClassify(twdtw_dist,format="GTiff",overwrite=TRUE)
> plot(x=land_cover_maps,type="maps")
> twdtw_assess <- twdtwAssess(object =twdtw_dist , y = validation_samples,proj4string = proj_str, conf.int = .95, rm.nosample = TRUE) 
Error in twdtwAssess.twdtwRaster(object, y, labels, id.labels, proj4string,  : 
  samples starting date not found, the argument 'y' must have a column called 'from'

**Comment by Mengshiyao** [comment]
the Error still comes out

**Comment by vwmaus** [comment]
please read the documentation of the function `?twdtwAssess` it requires a classified `object = land_cover_maps` and sampels `y = validation_samples` in the same format as `field_samples`.

**Comment by Mengshiyao** [comment]
``library(dtwSat)
 setwd("D:/Program Files/R/R-3.5.1/library/dtwSat/champaign_stack_cut_bip_tiff")
 field_samples <- read.csv("example1.4.csv", sep=",", stringsAsFactors = FALSE)
 field_samples$from = as.Date(field_samples$from)
 field_samples$to = as.Date(field_samples$to)
 dates <- scan("timeline",what="date")
  blue <- brick("cp_blue.tif")
  green <- brick("cp_green.tif")
  nir <- brick("cp_nir.tif")
  red <- brick("cp_red.tif")
  swir1 <- brick("cp_swir1.tif")
  swir2 <- brick("cp_swir2.tif")
  raster_timeseries <- twdtwRaster(blue,green,nir,red,swir1,swir2,timeline=dates)
  head(field_samples,10)
  proj_str <- scan("sample1_projection",what="character")
  library(caret)
  set.seed(1)
   I <- unlist(createDataPartition(field_samples$label,p=0.25))
  training_samples <- field_samples[I,  ]
  validation_samples <- field_samples[-I, ]
  training_ts<-getTimeSeries(raster_timeseries,y=training_samples,proj4string=proj_str)
  validation_ts<-getTimeSeries(raster_timeseries,y=validation_samples,proj4string=proj_str)
  temporal_patterns <-createPatterns(training_ts,freq=8,formula=y~s(x))
   log_fun <- logisticWeight(-0.1,50)
  beginCluster()
  twdtw_dist <- twdtwApplyParallel(x=raster_timeseries,y=temporal_patterns,overlap=0.5,weight.fun=log_fun,overwrite=TRUE,format="GTiff",progress="text")
  endCluster()
 land_cover_maps <- twdtwClassify(twdtw_dist)
  twdtw_assess <- twdtwAssess(object=land_cover_maps, y=validation_samples, proj4string=proj_str, conf.int=.95, rm.nosample=TRUE)

Error in to - from : non-numeric argument to binary operator

i convert the column 'from' and 'to'  to date ,but the same error as before

where is the problem...

**Comment by Mengshiyao** [comment]
here are some information about my data

 >dates 
 [1] "2017-02-03" "2017-03-07" "2017-03-16" "2017-05-10" "2017-06-11"
 [6] "2017-06-20" "2017-06-27" "2017-07-29" "2017-08-23" "2017-09-15"
[11] "2017-09-24" "2017-10-01" "2017-10-17" "2017-10-26" "2017-11-27"
> head(land_cover_maps)
An object of class "twdtwRaster"
Time series layers: Distance 
Time range: 2017-11-03 ... 2017-11-03     ## i don'tknow what's this ,i never use this date.
dimensions: 1 400 400 1 (nlayers, nrow, ncol, length)
resolution: 30 30  (x, y)
extent    : 375495 387495 4417245 4429245 (xmin, xmax, ymin, ymax)
coord.ref.: +proj=utm +zone=16 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
> head(validation_samples)
  latitude longitude       from         to   label
1 40.00213 -88.34123 2017-02-03 2017-11-27 soybean
2 40.00214 -88.34052 2017-02-03 2017-11-27 soybean
3 40.00213 -88.34088 2017-02-03 2017-11-27 soybean
4 40.00186 -88.34122 2017-02-03 2017-11-27 soybean
5 40.00186 -88.34087 2017-02-03 2017-11-27 soybean
6 40.00187 -88.34052 2017-02-03 2017-11-27 soybean

**Comment by vwmaus** [comment]
Please install the development version from Github
``` r
install.packages("devtools")
devtools::install_github("vwmaus/dtwSat")
```
then use the argument `start_date` in
``` r
twdtw_assess <- twdtwAssess(object=land_cover_maps, y=validation_samples, proj4string=proj_str, conf.int=.95, start_date = dates[1])
```
