### ISSUE TITLE
replace this with a classification period (from, to) in the object rasterTimeSeries

### ISSUE THREAD

**Issue by vwmaus** [vwmaus/dtwSat#25]
https://github.com/vwmaus/dtwSat/blob/a3e0bf0fed7eb530ec09d5cf2e0e147c88e2812d/R/twdtwAssess.R#L196

**Comment by Mengshiyao** [comment]
can't use
"install.packages("devtools")
devtools::install_github("vwmaus/dtwSat")" in R ,it report error.

and can't install the package "dtwSat-master.zip" download from your Github. 

how to use your package correctly???

**Comment by Mengshiyao** [comment]
> install.packages("C:/Users/Administrator/Desktop/dtwSat-master.zip", repos = NULL, type = "source")
In R CMD INSTALL

fill to install

**Comment by Mengshiyao** [comment]
> install.packages("C:/Users/Administrator/Desktop/dtwSat_0.2.4.tar.gz", repos = NULL, type = "source")
* installing *source* package 'dtwSat' ...
** 成功将'dtwSat'程序包解包并MD5和检查
** libs

*** arch - i386
E:/Program Files/Rtools/mingw_32/bin/gfortran      -O3  -mtune=generic -c bestmatches.f -o bestmatches.o
make: E:/Program: Command not found
make: *** [E:/Program Files/R/R-3.5.1/etc/i386/Makeconf:232: bestmatches.o] Error 127
ERROR: compilation failed for package 'dtwSat'
* removing 'E:/Program Files/R/R-3.5.1/library/dtwSat'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/Users/Administrator/Desktop/dtwSat_0.2.4.tar.gz’ had non-zero exit status

failed to install either

**Comment by Mengshiyao** [comment]
i can use your package download inside RGui  CRAN ,but can't edit your source code caus there is no .R file in R root directory "library\dtwSat\lib".  
how to use your package correctly???
