### ISSUE TITLE
Plotting cross validation object doesn't work properly

### ISSUE THREAD

**Issue by LRoters** [vwmaus/dtwSat#29]
Hello,
plotting a cross validation object shows the user's accuracy double, but not the producer's accuracy.
Here is the code:
```
cross_validation <- twdtwCrossValidate(field_samples_ts, times=100, p=0.1,freq=8,formula=y~s(x,bs="cc"), weight.fun = log_fun)
plot (cross_validation, conf.int = .95)
```
Even in the paper from Maus: dtwSat: Time-Weighted Dynamic Time Warping for Satellite Image Time Series Analysis in R (https://github.com/vwmaus/dtwSat/blob/master/inst/doc/applying_twdtw.pdf) is this plotting error.
Thank you for your help!

**Comment by vwmaus** [comment]
@LRoters many thanks for pointing out the problem. It is fixed now, please install the development version from Github:
```r
install.packages("devtools")
devtools::install_github("vwmaus/dtwSat")
```

**Comment by LRoters** [comment]
Yes it works. Thank you!
