### ISSUE TITLE
issue in create pattern from satellite  time-series

### ISSUE THREAD

**Issue by devi2019** [vwmaus/dtwSat#47]
Dear All, 

I have worked on Sentinel 1A time-series data to create temporal pattern from 28 no. of time series data. But i am getting an error as follows and  Here is my R code for which I got an error :

> temporal_patterns <-createPatterns(validation_ts, freq = 10, formula = y ~ s(x,k=9))
Error in smooth.construct.tp.smooth.spec(object, dk$data, dk$knots) : 
  A term has fewer unique covariate combinations than specified maximum degrees of freedom
> plot(temporal_patterns, type = "patterns") + theme(legend.position = c(.8, .21))
Error in plot(temporal_patterns, type = "patterns") : 
  object 'temporal_patterns' not found

My code in getting temporal pattern from sentinel-1A data
library(dtwSat)
library(caret)
library(readxl)
rm(list = ls())
setwd("G:/Sentinel 1A/TWDTW trial")
rvi <- brick(paste("RVIS16.tif", sep = "/"))
dates <- scan(paste("timeline", sep = "/"), what = "dates")
raster_timeseries <- twdtwRaster(rvi, timeline = dates)
field_samples <- read_excel("Field_sample s1anew - Copy.xlsx",sheet=1)
field_samples = as.data.frame(field_samples, stringsAsFactors = FALSE)
field_samples$from = as.Date(field_samples$from)
field_samples$to = as.Date(field_samples$to)
head(field_samples,10)
proj_str <- scan("sample1_projection",what="character")
proj_str 
field_samples_ts<-getTimeSeries(raster_timeseries,y=field_samples,proj4string=proj_str)
field_samples_ts
head(field_samples_ts,10)
library(caret)
library(splines)
set.seed(1)
I <- unlist(createDataPartition(field_samples$label,p=0.1))
validation_samples <- field_samples[-I, ]
training_samples <- field_samples[I, ]
training_ts <- getTimeSeries(raster_timeseries, y = training_samples, proj4string = proj_str)
validation_ts <- getTimeSeries(raster_timeseries, y = validation_samples, proj4string = proj_str)
temporal_patterns <-createPatterns(validation_ts, freq = 10, formula = y ~ s(x,k=9))
plot(temporal_patterns, type = "patterns") + theme(legend.position = c(.8, .21))

**Comment by vwmaus** [comment]
The error message is clear. The error is in `s(x,k=9))`, check the documentation of `?mgcv::s`.
