### ISSUE TITLE
Different geographical locations for Temporal Patterns and Actual Raster Bands

### ISSUE THREAD

**Issue by Randy6668** [vwmaus/dtwSat#48]
Dear all, I'm currently attempting to do a TWDTW classification for a region without any known samples (Region A), but I do have sample points from a nearby region (and associated time series data; Region B). I'm attempting to build the temporal patterns data from Region B and use them to classify Region A. But from what I understand, twdtwApply requires both training and validation rasters to be the same. 

Is there any workabout for this? Been looking through other available functions, but could not find much so far. Thanks!

**Comment by TheSl0thzilla** [comment]
I run into the same problem. Have you found a solution?

**Comment by vwmaus** [comment]
Build the patterns for region B, where you have samples, then classify region A using these patterns. That is no problem for TWDTW. Differently from ML approaches, TWDTW generalises well across space and time, as long as the regions are still within the same clime zone. If possible please report your experience here.
