### ISSUE TITLE
Match and Alignment for the Raster Time series datasets ?

### ISSUE THREAD

**Issue by devi2019** [vwmaus/dtwSat#50]
How to find out Match and Alignment for the Raster Time series datasets?

I am very new to Dtw-Sat. I want to findout Match and Alignment of raster time series. How to get it ?Say sentinel 2 time series datasets (Regarding Crop classification) .

**Comment by vwmaus** [comment]
Match and Alignment are only possible for `twdtwTimeSeries` objects not for `twdtwRaster`.
