### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by zmx123-cloud** [vwmaus/dtwSat#54]
Hello, I would like to ask you a question. Whether TWDTW can measure similarity in the absence of temporal patterns. I want to modify the source code if I can, but I can't see the source code, or I can't debug the twdtwApply() method, and I want to know why or what to do about it. Looking forward to your reply. Thank you very much.

**Comment by vwmaus** [comment]
Thank you for your message. TWDTW is designed for seasonal time series data. For non-seasonal sequential data, I recommend exploring the DTW literature.
