### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [vwmaus/dtwSat#56]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by vwmaus** [comment]
@rsbivand thank you for the reminder. Working on a fix for this is scheduled to start in mid-June.

**Comment by rsbivand** [comment]
@vwmaus @appelmar @nk027  Only three months remain before retiring packages are archived. I don't see any movement in this repo. Untried - drop `rgdal` completely and add `sf` as `Suggests:`. Then run check as suggested in https://r-spatial.org/r/2023/05/15/evolution4.html (current `sp` (status 2), no retiring packages on library path).

**Comment by vwmaus** [comment]
@rsbivand I started working on this.

**Comment by vwmaus** [comment]
dtwSat 1.0.0 removes all obsolete dependencies.
